### ISSUE TITLE
Internal Documentations Overhaul

### ISSUE THREAD

**Issue by user5423** [AR-Reshare/AR-Reshare#58]
The internal docs need to be overhauled before the user manual deadlines

For the pipeline section, I have provided a high-level abstract design explanation - but I still rely on the internal docs to provide the lower level technical explanations. Therefore these need to be solid

**Comment by user5423** [comment]
API Key has been suspended

**Comment by zshepherd01** [comment]
Most of the internal documentation has been overhauled. @user5423 could you provide docstrings for your parts of the code (`classes/securityvalidation.js` and `classes/email.js`)?

**Comment by zshepherd01** [comment]
Updated the internal README files in the dev-internaldocs branch

**Comment by user5423** [comment]
@jshepherd01 I've created docstrings for both `classes/securityvalidation.js` and `classes/email.js` on the dev-documentation branch (I though the dev-internaldocs branch had been deleted)

**Comment by user5423** [comment]
#63 and #62 should close this issue

**Comment by zshepherd01** [comment]
Closed by #63
