### ISSUE TITLE
Live Deployment Token Issues

### ISSUE THREAD

**Issue by user5423** [AR-Reshare/AR-Reshare#59]
There are issues with the live deployment where requests are being sent but due to certain token issues, we are receiving 4xx errors

**Comment by zshepherd01** [comment]
To elaborate, these issues are present specifically when making a request from the API Documentation pages. This is because the pages automatically include an Authorization header in the request, but populate it with the default value 123 instead of a valid token.

**Comment by zshepherd01** [comment]
Three aspects to this: Elements, Service, Docs

Elements side: we can remove the try-it section across all pages in the docs. Easiest solution, doesn't touch the service itself

Service side: I can identify the default value and manually white-list it as "if this value is given, act like no value is given". This would work, but I don't like the idea of tweaking the service itself just to make the demo work

OAS docs side: Not sure, is there a way to manually set the example authorisation header to blank? The same way the example body of /account/create has that robot guy's name in it?
